name: CI

# 同時実行制限を追加
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          cache-version: v1-${{ github.sha }}  # キャッシュバージョンを追加
      
      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager --skip-files EOLRuby

  scan_js:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          cache-version: v1-${{ github.sha }}  # キャッシュバージョンを追加
      
      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          cache-version: v1-${{ github.sha }}  # キャッシュバージョンを追加
      
      - name: Lint code for consistent style
        run: bin/rubocop -f github